"""add multinode tables

Revision ID: de7744915ea6
Revises: 1538bd14b937
Create Date: 2026-03-30 01:24:52.716909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7744915ea6'
down_revision: Union[str, None] = '1538bd14b937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extend alerttype enum with path_deviation (PostgreSQL 15 supports this in transaction)
    op.execute(sa.text("ALTER TYPE alerttype ADD VALUE IF NOT EXISTS 'path_deviation'"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('factory_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('identification_method', sa.Enum('camera', 'manual', name='identificationmethod'), nullable=False),
    sa.Column('is_gate', sa.Boolean(), nullable=False),
    sa.Column('camera_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('path_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('factory_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('path_template_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('entry', 'exit', 'any', name='stepdirection'), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['path_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_journeys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('factory_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'deviated', name='journeystatus'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['path_templates.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journey_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('gate_event_id', sa.Uuid(), nullable=True),
    sa.Column('checkpoint_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('entry', 'exit', name='journeydirection'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deviation', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.ForeignKeyConstraint(['gate_event_id'], ['gate_events.id'], ),
    sa.ForeignKeyConstraint(['journey_id'], ['vehicle_journeys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vehicles', sa.Column('current_checkpoint_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('vehicles_current_checkpoint_id_fkey', 'vehicles', 'checkpoints', ['current_checkpoint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE: PostgreSQL does not support removing enum values; path_deviation enum value remains
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vehicles_current_checkpoint_id_fkey', 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'current_checkpoint_id')
    op.drop_table('journey_events')
    op.drop_table('vehicle_journeys')
    op.drop_table('path_template_steps')
    op.drop_table('path_templates')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###
